# Base Image: 
FROM pyspark-image:3.5.0

# Set the working directory inside the container
WORKDIR /pysparkapp

# Copy src code into container
COPY . /pysparkapp

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the required Python packages
RUN pip install -r requirements.txt


# Execute scripts
CMD ["pyspark", "main.py"]