# Base Image: from the official Python 3.11.3 image
FROM python:3.11.3

# Set the working directory inside the container
WORKDIR /app

# Copy src code into container
COPY . /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the required Python packages
RUN pip install -r requirements.txt


# Execute scripts
CMD ["python", "detect.py"]